version: '3'
services:
  db:
    container_name: admin_panel_db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    env_file:
      - .env
    volumes:
      - ./app/db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data/
    expose:
      - 5432

  app:
    container_name: admin_panel_app
    restart: always
    build:
        context: .
        dockerfile: ./app/Dockerfile
    env_file: .env
    volumes:
      - ./app/logs:/app/logs
      - static:/app/data/static
      - media:/app/data/media
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    container_name: admin_panel_nginx
    restart: always
    image: nginx:1.23.0
    volumes:
      - static:/data/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - app
      - db
    ports:
      - 80:80
    

volumes:
  static:
  media:
  db_data:
